package com.atdaiwa.crowd.dao;

import com.atdaiwa.crowd.entity.Auth;
import com.atdaiwa.crowd.entity.AuthExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    long countByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    int deleteByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    int insert(Auth record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    int insertSelective(Auth record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    List<Auth> selectByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    Auth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    int updateByExampleSelective(@Param("record") Auth record, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    int updateByExample(@Param("record") Auth record, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    int updateByPrimaryKeySelective(Auth record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table tbl_auth
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    int updateByPrimaryKey(Auth record);

    List<Integer> selectAssignedAuthIdByRoleId(Integer roleId);

    void deleteOldRelationship(Integer roleId);

    void insertNewRelationship(@Param("roleId") Integer roleId, @Param("authIdList") List<Integer> authIdList);
}