package com.atdaiwa.crowd.entity;

public class Admin {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column tbl_admin.id
     *
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column tbl_admin.login_account
     *
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    private String loginAccount;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column tbl_admin.user_password
     *
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column tbl_admin.user_name
     *
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column tbl_admin.email
     *
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database column tbl_admin.create_time
     *
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    private String createTime;

    public Admin() {
        super();
    }

    public Admin(Integer id, String loginAccount, String userPassword, String userName, String email,
                 String createTime) {
        super();
        this.id = id;
        this.loginAccount = loginAccount;
        this.userPassword = userPassword;
        this.userName = userName;
        this.email = email;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column tbl_admin.id
     *
     * @return the value of tbl_admin.id
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column tbl_admin.id
     *
     * @param id the value for tbl_admin.id
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column tbl_admin.login_account
     *
     * @return the value of tbl_admin.login_account
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column tbl_admin.login_account
     *
     * @param loginAccount the value for tbl_admin.login_account
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column tbl_admin.user_password
     *
     * @return the value of tbl_admin.user_password
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column tbl_admin.user_password
     *
     * @param userPassword the value for tbl_admin.user_password
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column tbl_admin.user_name
     *
     * @return the value of tbl_admin.user_name
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column tbl_admin.user_name
     *
     * @param userName the value for tbl_admin.user_name
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column tbl_admin.email
     *
     * @return the value of tbl_admin.email
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column tbl_admin.email
     *
     * @param email the value for tbl_admin.email
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value
     * of the database column tbl_admin.create_time
     *
     * @return the value of tbl_admin.create_time
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of
     * the database column tbl_admin.create_time
     *
     * @param createTime the value for tbl_admin.create_time
     * @mbg.generated Thu Jan 27 16:51:59 JST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    @Override
    public String toString() {
        return "Admin [id=" + id + ", loginAccount=" + loginAccount + ", userPassword=" + userPassword + ", userName="
                + userName + ", email=" + email + ", createTime=" + createTime + "]";
    }
}