package com.atdaiwa.crowd.entity;

public class Auth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth.id
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth.name
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth.title
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_auth.category_id
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    private Integer categoryId;

    public Auth() {
		super();
	}

	public Auth(Integer id, String name, String title, Integer categoryId) {
		super();
		this.id = id;
		this.name = name;
		this.title = title;
		this.categoryId = categoryId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth.id
     *
     * @return the value of tbl_auth.id
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth.id
     *
     * @param id the value for tbl_auth.id
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth.name
     *
     * @return the value of tbl_auth.name
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth.name
     *
     * @param name the value for tbl_auth.name
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth.title
     *
     * @return the value of tbl_auth.title
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth.title
     *
     * @param title the value for tbl_auth.title
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_auth.category_id
     *
     * @return the value of tbl_auth.category_id
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_auth.category_id
     *
     * @param categoryId the value for tbl_auth.category_id
     *
     * @mbg.generated Sat Apr 09 22:07:58 JST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

	@Override
	public String toString() {
		return "Auth [id=" + id + ", name=" + name + ", title=" + title + ", categoryId=" + categoryId + "]";
	}
}