package com.atdaiwa.crowd.entity;

import java.util.ArrayList;
import java.util.List;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_menu.id
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_menu.pid
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_menu.NAME
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_menu.url
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_menu.icon
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    private String icon;
    
    private List<Menu> children = new ArrayList<Menu>();
    
    public Menu() {
		super();
	}

	public Menu(Integer id, Integer pid, String name, String url, String icon, List<Menu> children, boolean open) {
		super();
		this.id = id;
		this.pid = pid;
		this.name = name;
		this.url = url;
		this.icon = icon;
		this.children = children;
		this.open = open;
	}

	private boolean open = true;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_menu.id
     *
     * @return the value of tbl_menu.id
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_menu.id
     *
     * @param id the value for tbl_menu.id
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_menu.pid
     *
     * @return the value of tbl_menu.pid
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_menu.pid
     *
     * @param pid the value for tbl_menu.pid
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_menu.NAME
     *
     * @return the value of tbl_menu.NAME
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_menu.NAME
     *
     * @param name the value for tbl_menu.NAME
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_menu.url
     *
     * @return the value of tbl_menu.url
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_menu.url
     *
     * @param url the value for tbl_menu.url
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_menu.icon
     *
     * @return the value of tbl_menu.icon
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_menu.icon
     *
     * @param icon the value for tbl_menu.icon
     *
     * @mbg.generated Mon Apr 04 00:07:03 JST 2022
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

	public List<Menu> getChildren() {
		return children;
	}

	public void setChildren(List<Menu> children) {
		this.children = children;
	}

	public boolean isOpen() {
		return open;
	}

	public void setOpen(boolean open) {
		this.open = open;
	}

	@Override
	public String toString() {
		return "Menu [id=" + id + ", pid=" + pid + ", name=" + name + ", url=" + url + ", icon=" + icon + ", children="
				+ children + ", open=" + open + "]";
	}
}