package com.atdaiwa.crowd.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.id
     *
     * @mbg.generated Fri Mar 18 14:15:48 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.NAME
     *
     * @mbg.generated Fri Mar 18 14:15:48 JST 2022
     */
    private String name;

    public Role() {
		super();
	}

	public Role(Integer id, String name) {
		super();
		this.id = id;
		this.name = name;
	}
	
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.id
     *
     * @return the value of tbl_role.id
     *
     * @mbg.generated Fri Mar 18 14:15:48 JST 2022
     */
    
    public Integer getId() {
        return id;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.id
     *
     * @param id the value for tbl_role.id
     *
     * @mbg.generated Fri Mar 18 14:15:48 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.NAME
     *
     * @return the value of tbl_role.NAME
     *
     * @mbg.generated Fri Mar 18 14:15:48 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.NAME
     *
     * @param name the value for tbl_role.NAME
     *
     * @mbg.generated Fri Mar 18 14:15:48 JST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	@Override
	public String toString() {
		return "Role [id=" + id + ", name=" + name + "]";
	}
}